from md2pdf.core import md2pdf 
from datetime import date
import uuid

dummy = '''Problem Description:\nBMW is a leading luxury car manufacturer with a global presence. The company is facing challenges related to the high volume of customer complaints that it receives on a regular basis. The BMW customer service team is having a difficult time keeping up with the growing volume of customer complaints which is leading to customer dissatisfaction and lost revenue.\n\nSolutions Being Used So Far:\nThe BMW customer service team currently handles customer complaints through traditional channels such as phone and email. They also have an internal team dedicated to handling social media complaints. However, these traditional methods are not scalable enough to handle the growing volume of complaints.\n\nExpected Business Value:\nImplementing AI systems to address customer complaints can help BMW improve customer satisfaction, reduce customer churn and lost revenue. By automating complaint management, BMW can improve the efficiency of complaint resolution and increase the response time for customers. This can lead to improved customer loyalty and lead to better revenue growth.\n\nHow AI can be Applied:\nBMW can deploy AI systems such as natural language processing (NLP) and machine learning algorithms to process and categorize the incoming complaints in real-time. They can further customize responses for customers through chatbots which can address common complaints such as vehicle performance, maintenance, or functionality. BMW can also use predictive analytics to identify common complaints and take steps to address them proactively.\n\nPotential Costs and Risks:\nThe initial cost of implementing AI solutions may be high in terms of hardware, software, and expert resources. Moreover, there may be concerns around data privacy and security, as well as potential resistance among the workforce to relinquish some of their traditional roles in customer service. BMW should also consider the long-term cost of maintaining and upgrading AI systems, as well as the risk of liability if an AI-powered solution gives wrong or inappropriate answers.\n\nData sources required by this use case:\nTo implement AI systems for complaint management, BMW would need to integrate with its existing customer relationship management (CRM) and customer experience (CX) systems. The data required would include customer profiles, complaints history, vehicle data, and other relevant customer details. BMW can also utilize data from social media channels, public forums, and online discussion boards to understand customer sentiments and opinions.
'''
titles = [
    "Problem Description:",
    "Solutions Being Used So Far:",
    "Expected Business Value:",
    "How AI can be Applied:",
    "Potential Costs and Risks:",
    "Data sources required by this use case:"
]

def isTitle(s):
    if s.strip() in titles:
        return True
    return False


md_header1 = '''
<img src="https://i.ibb.co/G3sx1Q3/rsz-1full-loco.png">
<h1> Report for '''

md_header2 = ''' </h1>

---

'''

md_footer1 = '''
 
--- 

<img src="https://i.ibb.co/G3sx1Q3/rsz-1full-loco.png">


This report was generated by CanAI
<br>
'''

def generate_pdf(companyName, report):
    blocks = report.split('\n')
    md_data = md_header1 + companyName + md_header2
    for s in blocks:
        if isTitle(s):
            md_data += f"<h3> {s} </h3>\n"
        else:
            md_data += f"{s}\n"
    md_data += md_footer1 + str(date.today()) + "\n"
    pdfName = str(uuid.uuid4())+".pdf"
    md2pdf("./pdfs/"+pdfName, md_content=md_data, css_file_path="style.css")
    return pdfName


